# This is a basic workflow to help you get started with Actions
name: Buid and Deploy Spring Boot ci AWS EC2

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -f APIServerMoveMovie/pom.xml clean package
      
    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp APIServerMoveMovie/target/*.jar deploy/

    - name: Make zip file
      run: zip -r ./movemovie.zip deploy/
      shell: bash
